# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AnalyzeSnapJob`.
# Please instead update this file by running `bin/tapioca dsl AnalyzeSnapJob`.

class AnalyzeSnapJob
  class << self
    sig { params(snap: ::Snap).returns(T.any(AnalyzeSnapJob, FalseClass)) }
    def perform_later(snap); end

    sig { params(snap: ::Snap).void }
    def perform_now(snap); end
  end
end
