# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AnalyzeSnapsJob`.
# Please instead update this file by running `bin/tapioca dsl AnalyzeSnapsJob`.

class AnalyzeSnapsJob
  class << self
    sig { returns(T.any(AnalyzeSnapsJob, FalseClass)) }
    def perform_later; end

    sig { void }
    def perform_now; end
  end
end
