# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ProcessSnapsJob`.
# Please instead update this file by running `bin/tapioca dsl ProcessSnapsJob`.

class ProcessSnapsJob
  class << self
    sig { returns(T.any(ProcessSnapsJob, FalseClass)) }
    def perform_later; end

    sig { void }
    def perform_now; end
  end
end
